# Copyright 2009, Peter A. Bigot
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain a
# copy of the License at:
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""Binding classes for types referenced by the attribute and attribute
group declarations in the XML namespace
(http://www.w3.org/XML/1998/namespace).

The content of this module was generated by PyXB and is coupled to the
components defined in L{pyxb_114.namespace.builtin._XML}.

"""

# ./pyxb_114/standard/bindings/raw/xml_.py
# PyXB bindings for NamespaceModule
# Generated 2009-07-25 13:37:53.257717 by PyXB version 0.5.2
import pyxb_114
import pyxb_114.binding
import pyxb_114.utils.utility
import pyxb_114.utils.domutils
import sys

# Unique identifier for bindings created at the same time
_GenerationUID = pyxb_114.namespace.builtin.BuiltInObjectUID

# Import bindings for namespaces imported into schema

Namespace = pyxb_114.namespace.NamespaceForURI('http://www.w3.org/XML/1998/namespace', create_if_missing=True)
ModuleRecord = Namespace.lookupModuleRecordByUID(_GenerationUID, create_if_missing=True)
ModuleRecord._setModule(sys.modules[__name__])

# Atomic SimpleTypeDefinition
class STD_ANON_space (pyxb_114.binding.datatypes.NCName, pyxb_114.binding.basis.enumeration_mixin):
    """No information"""

    _ExpandedName = None
STD_ANON_space._CF_enumeration = pyxb_114.binding.facets.CF_enumeration(value_datatype=STD_ANON_space, enum_prefix=None)
STD_ANON_space.default = STD_ANON_space._CF_enumeration.addEnumeration(unicode_value=u'default')
STD_ANON_space.preserve = STD_ANON_space._CF_enumeration.addEnumeration(unicode_value=u'preserve')
STD_ANON_space._InitializeFacetMap(STD_ANON_space._CF_enumeration)

# Atomic SimpleTypeDefinition
class STD_ANON_emptyString (pyxb_114.binding.datatypes.string, pyxb_114.binding.basis.enumeration_mixin):
    """No information"""

    _ExpandedName = None
STD_ANON_emptyString._CF_enumeration = pyxb_114.binding.facets.CF_enumeration(value_datatype=STD_ANON_emptyString, enum_prefix=None)
STD_ANON_emptyString.emptyString = STD_ANON_emptyString._CF_enumeration.addEnumeration(unicode_value=u'')
STD_ANON_emptyString._InitializeFacetMap(STD_ANON_emptyString._CF_enumeration)

# Union SimpleTypeDefinition
# superclasses pyxb_114.binding.datatypes.anySimpleType
class STD_ANON_lang (pyxb_114.binding.basis.STD_union):
    """Simple type that is a union of pyxb_114.binding.datatypes.language, STD_ANON_emptyString"""

    _ExpandedName = None
    _MemberTypes = ( pyxb_114.binding.datatypes.language, STD_ANON_emptyString, )
STD_ANON_lang._CF_enumeration = pyxb_114.binding.facets.CF_enumeration(value_datatype=STD_ANON_lang)
STD_ANON_lang._CF_pattern = pyxb_114.binding.facets.CF_pattern()
STD_ANON_lang._InitializeFacetMap(STD_ANON_lang._CF_enumeration,
   STD_ANON_lang._CF_pattern)
